import "dotenv/config";
import { GoogleGenAI } from "@google/genai";
import { InMemoryVectorStore } from "../02-vector-store/vector-store.js";
import { semanticChunkText } from "../01-semantic-chunker/semantic-chunker.js";

const apiKey = process.env.GEMINI_API_KEY;
const ai = new GoogleGenAI(apiKey ? { apiKey } : {});

export interface SourceCitation {
  id?: string;
  text: string;
  score: number;
  metadata?: Record<string, any>;
}

export interface RAGResponse {
  answer: string;
  sources: SourceCitation[];
  hasSufficientContext: boolean;
}

export interface RAGPipelineOptions {
  model?: string;
  similarityCutoff?: number;
  temperature?: number;
  systemInstruction?: string;
}

export class RAGPipeline {
  private model: string;
  private similarityCutoff: number;
  private temperature: number;
  private systemInstruction: string;

  constructor(
    private vectorStore: InMemoryVectorStore,
    options: RAGPipelineOptions = {}
  ) {
    this.model = options.model ?? "gemini-3.6-flash";
    this.similarityCutoff = options.similarityCutoff ?? 0.50;
    this.temperature = options.temperature ?? 0.1;
    this.systemInstruction =
      options.systemInstruction ??
      `You are a high-precision technical assistant. Your task is to answer the user's question based EXCLUSIVELY on the fragments provided within the <context> block.

Critical Grounding Rules:
1. Do not use external knowledge or make assumptions not explicitly stated in the context.
2. If the answer cannot be determined strictly from the provided context, state clearly and concisely that you do not have sufficient information in the knowledge base.
3. Always cite the corresponding supporting source using the format [Source X].
4. Maintain factual consistency and do not extrapolate numbers, dates, or specifications.`;
  }

  /**
   * Semantically chunks and indexes a raw text document into the vector store.
   * @param rawText Document content to ingest.
   * @param metadata Optional metadata to attach to the chunks.
   * @returns Number of indexed semantic chunks.
   */
  async ingestDocument(
    rawText: string,
    metadata: Record<string, any> = {}
  ): Promise<number> {
    const chunks = await semanticChunkText(rawText);
    if (chunks.length > 0) {
      await this.vectorStore.addDocuments(chunks, metadata);
    }
    return chunks.length;
  }

  /**
   * Executes a grounded RAG query against the indexed knowledge base.
   * @param question User query or prompt.
   * @param topK Maximum number of relevant chunks to retrieve.
   */
  async query(question: string, topK = 2): Promise<RAGResponse> {
    // 1. Retrieve top-K relevant chunks from vector store
    const relevantChunks = await this.vectorStore.search(question, topK);

    // 2. Guardrail: Verify relevance against similarity threshold
    if (relevantChunks.length === 0 || relevantChunks[0].score < this.similarityCutoff) {
      return {
        answer: "I do not have sufficient verified information in my knowledge base to answer this question.",
        sources: relevantChunks,
        hasSufficientContext: false,
      };
    }

    // 3. Construct delimited context with source identifiers
    const contextText = relevantChunks
      .map(
        (c, i) =>
          `[Source ${i + 1}] (Relevance Score: ${(c.score * 100).toFixed(1)}%):\n${c.text}`
      )
      .join("\n\n");

    const userPrompt = `
<context>
${contextText}
</context>

Question: ${question}
`;

    // 4. Generate grounded inference with generative LLM
    try {
      const response = await ai.models.generateContent({
        model: this.model,
        contents: userPrompt,
        config: {
          systemInstruction: this.systemInstruction,
          temperature: this.temperature,
        },
      });

      return {
        answer: response.text?.trim() || "No response generated by the model.",
        sources: relevantChunks,
        hasSufficientContext: true,
      };
    } catch (error) {
      // Fallback if primary model encounters a transient issue
      console.warn(`[RAGPipeline] Warning: Fallback triggered on model generation error:`, error);
      throw error;
    }
  }
}
